### ISSUE TITLE
Will resource files be uploaded?

### ISSUE THREAD

**Issue by nevermorewish** [kantam5/UE5-Action-Adventure-Sekiro-Clone#1]
Can  purchase resource files?

**Comment by kantam5** [comment]
Resource files cannot be shared because they were purchased from the marketplace. The asset I used is as follows.
- https://www.unrealengine.com/marketplace/en-US/item/67de339423064a1fbde59567ef97f5f9?lang=en-US
- https://www.unrealengine.com/marketplace/en-US/item/60c4de5e564a49bcafc8753ad38ef017
- https://www.unrealengine.com/marketplace/en-US/item/5b7704ca126f4ae68e5721630d924b6b
- https://www.unrealengine.com/marketplace/en-US/item/7c0af7bc717b4fb9933d86b0958463be
